#!/usr/bin/env python3

import argparse
from Bocelli import Bocelli

if __name__=="__main__":
    parser = argparse.ArgumentParser(description="Bocelli provides a simple node to speak and listen to people")

    args = parser.parse_args()

    Bocelli.main()